@startuml
!define RECTANGLE class
left to right direction
skinparam packageStyle rect
actor Customer
actor Admin

rectangle "Интернет-магазин" {
    usecase "Поиск товаров" as UC1
    usecase "Просмотр товаров" as UC2
    usecase "Добавление товара в корзину" as UC3
    usecase "Оформление заказа" as UC4
    usecase "Просмотр истории заказов" as UC5
    usecase "Управление товарами" as UC6
    usecase "Управление заказами" as UC7
}

Customer -> UC1
Customer -> UC2
Customer -> UC3
Customer -> UC4
Customer -> UC5

Admin -> UC6
Admin -> UC7

UC4 --> UC5 : extends
@enduml